Scr.add( ...
    Epoch('name',    'Begin', ...
          'preProc', {@() waitUntil(1)}, ...
          'hide',    {'_all'}, ...
          'show',    {'FP', 'Targ'}, ...
          'read',    'Fix', ...
          'waitFor', 1, ...
          'jump',    {'fixAcq',  'Motion', {}
                      'timeOut', 'TimeOut', {}} ...
       ));

