function tf = validpath(d)
% tf = validpath(d)

[~,nam] = fileparts(d.name);

tf = exist(d.name, 'dir') ...
    && ~isempty(nam) ...
    && ~any(nam(1) == '.+@') ...
    && ~any(strcmp(nam, {'private', 'old', 'Data'})) ...
    && isempty(strfind(d.name, [filesep 'Data' filesep])) ...
    && ~strcmpStart(['Data' filesep], d.name);

% fprintf('%s - %s\n', d.name, nam);
% try
%     tf = exist(d.name, 'dir') % ...
%     tf = ~isempty(nam) % ...
%     tf = ~any(nam(1) == '.+@') % ...
%     tf = ~any(strcmp(nam, {'private', 'old', 'Data'})) % ...
%     tf = isempty(strfind(d.name, [filesep 'Data' filesep])) % ;    
%     tf = ~strcmpFirst(d.name, ['Data' filesep])
% %     assert(~strcmp(nam, 'OptimPlots'))
% catch err
%     warning(err_msg(err));
%     keyboard;
% end
% fprintf('-----\n');
end