function [cost,grad,hess] = cost_rtonly_drift0(b,rt_obs,rt_sem_obs,tnd)
%COST_RTONLY_DRIFT0
%    [COST,GRAD,HESS] = COST_RTONLY_DRIFT0(B,RT_OBS,RT_SEM_OBS,TND)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Aug-2016 10:05:28

cost = log(rt_sem_obs)+1.0./rt_sem_obs.^2.*(-rt_obs+tnd+b.^2).^2.*(1.0./2.0);
if nargout > 1
    grad = [b.*1.0./rt_sem_obs.^2.*(-rt_obs+tnd+b.^2).*2.0,0.0,0.0,1.0./rt_sem_obs.^2.*(rt_obs.*-2.0+tnd.*2.0+b.^2.*2.0).*(1.0./2.0)];
end
if nargout > 2
    hess = reshape([1.0./rt_sem_obs.^2.*(-rt_obs+tnd+b.^2).*2.0+b.^2.*1.0./rt_sem_obs.^2.*4.0,0.0,0.0,b.*1.0./rt_sem_obs.^2.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,b.*1.0./rt_sem_obs.^2.*2.0,0.0,0.0,1.0./rt_sem_obs.^2],[4,4]);
end
